export const CREATE_TASK = 'CREATE_TASK';
export const DELETE_TASK = 'DELETE_TASK';
export const TOGGLE_COMPLETE= 'TOGGLE_COMPLETE';
export const SET_VISIBILITY_ALL = 'VISIBLITY_ALL';
export const SET_VISIBILITY_COMPLETED = 'VISIBILITY_COMPLETED';
export const SET_VISIBILITY_UNCOMPLETED = 'VISIBILITY_UNCOMPLETED';
export const SET_ALERT_MESSAGE = 'SET_ALERT_MESSAGE';
export const CHANGE_FILTER = 'CHANGE_FILTER';

export const VISIBILITY_MODES =  {
  ALL : 'ALL',
  COMPLETED: 'COMPLETED',
  UNCOMPLETED: 'UNCOMPLETED'
}
