export const CREATE_TASK = 'CREATE_TASK';
export const TOGGLE_TASK = 'TOGGLE_TASK';
export const SET_VISIBILITY_ALL = 'VISIBLITY_ALL';
export const SET_VISIBILITY_COMPLETED = 'VISIBILITY_COMPLETED';
export const SET_VISIBILITY_UNCOMPLETED = 'VISIBILITY_UNCOMPLETED';

export const VISIBILITY_MODES =  {
  ALL : 'ALL',
  COMPLETED: 'COMPLETED',
  UNCOMPLETED: 'UNCOMPLETED'
}
